backend:
  name: git-gateway
  branch: main
  site_domain: aulabackend.netlify.app

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pagina_sites"
    label: "Gerenciar Sites"
    files:
      - name: "meus_sites"
        label: "Lista de Sites"
        file: "dados/sites.json"
        fields:
          - label: "Sites Desenvolvidos"
            name: "lista"
            widget: "list"
            fields:
              - {label: "Nome do Projeto", name: "titulo", widget: "string"}
              - {label: "Link do Site", name: "url", widget: "string"}
              - {label: "Imagem do Print", name: "imagem", widget: "image"}
              - label: "Compatibilidade Mobile"
                name: "mobile"
                widget: "select"
                options: ["Funciona Bem", "NÃ£o Funciona Bem"]

                default: "Funciona Bem"
